[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "manim-jm"
version = "0.1.0"
authors = [{ name = "Jay Mody", email = "jaykmody@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = ["manim", "numpy"]
